In [4]:
import get_EETs,My_CPM
import project_network_generater

ModuleNotFoundError: No module named 'Functions'

In [2]:
G=project_network_generater.project_network_generater(7)
G

array([[-1,  1,  3,  1,  7,  2,  5],
       [-1, -1,  5,  8, -1,  7,  6],
       [-1, -1, -1, 10,  5,  6,  5],
       [-1, -1, -1, -1,  8, -1,  0],
       [-1, -1, -1, -1, -1,  8, -1],
       [-1, -1, -1, -1, -1, -1,  8],
       [-1, -1, -1, -1, -1, -1, -1]])

In [3]:
get_EETs.get_EETs(G)

[0, 1, 6, 16, 24, 32, 40]

In [6]:
My_CPM.My_CPM()

NameError: name 'My_CPM' is not defined

In [9]:
import project_network_generater
import get_EETs,get_LETs,get_TFs
def My_CPM(n=30):
    G=project_network_generater.project_network_generater(n)
    EET=get_EETs.get_EETs(G)
    LET=get_LETs.get_LETs(G,EET)
    TFs_Dict=get_TFs.get_TFs(G,EET,LET)
    critical_Path=[]
    for i in list(TFs_Dict.keys()):
        if TFs_Dict[i]==0:
            critical_Path.append(i)
    return critical_Path

In [10]:
My_CPM()

['[1, 2]',
 '[2, 4]',
 '[4, 5]',
 '[5, 6]',
 '[6, 7]',
 '[7, 8]',
 '[8, 10]',
 '[10, 11]',
 '[11, 12]',
 '[12, 14]',
 '[14, 15]',
 '[15, 16]',
 '[16, 17]',
 '[17, 18]',
 '[18, 19]',
 '[19, 20]',
 '[20, 21]',
 '[21, 22]',
 '[22, 23]',
 '[23, 24]',
 '[24, 25]',
 '[25, 26]',
 '[26, 27]',
 '[27, 28]',
 '[28, 29]',
 '[29, 30]']

In [1]:
import My_CPM
My_CPM.My_CPM()

['[1, 3]',
 '[3, 4]',
 '[4, 5]',
 '[5, 6]',
 '[6, 7]',
 '[7, 8]',
 '[8, 9]',
 '[9, 10]',
 '[10, 11]',
 '[11, 12]',
 '[12, 13]',
 '[13, 14]',
 '[14, 15]',
 '[15, 16]',
 '[16, 17]',
 '[17, 18]',
 '[18, 19]',
 '[19, 20]',
 '[20, 21]',
 '[21, 22]',
 '[22, 23]',
 '[23, 24]',
 '[24, 25]',
 '[25, 27]',
 '[27, 30]']

In [4]:
import random
random.random()

0.9266057973939348

In [5]:
from random import randint,random
import numpy as np

def project_network_generater(n=30):
    G=np.ones((n,n))
    G*=-1
# Make sure node 1 :node n has a full connected path
    for i in range(n):
            for j in range(i+1,n):
                connect_index=random()   #uniform(0,1),decide whether the node is connected
                if connect_index<0.5:
                    G[i,j]=randint(-1,10)
                else:
                    G[i,j]=-1
    for i in range(n-1):
        j=i+1
        G[i,j]=randint(0,10)
# Ensuring at most 4 income
    for i in range(5,n):
        popout_List=[]
        while len(popout_List)<i-4:
            random_Popout_Index=randint(0,i-2)
            if  random_Popout_Index in popout_List:
                continue
            else:
                popout_List.append(random_Popout_Index)
        for item in popout_List:
            G[item,i]=-1
    return G

In [11]:
project_network_generater(8)

array([[-1.,  7.,  5., -1., -1., -1., -1., -1.],
       [-1., -1.,  4., -1., -1., -1., -1., -1.],
       [-1., -1., -1.,  1.,  4., -1.,  4.,  1.],
       [-1., -1., -1., -1.,  8.,  8.,  1., -1.],
       [-1., -1., -1., -1., -1., 10., -1., -1.],
       [-1., -1., -1., -1., -1., -1.,  9., -1.],
       [-1., -1., -1., -1., -1., -1., -1.,  0.],
       [-1., -1., -1., -1., -1., -1., -1., -1.]])

In [354]:
import project_network_generater_v2
import get_EETs,get_LETs,get_TFs
import numpy as np

def My_CPM(x=[],n=30):
    if x==[] and n !=30:
        print(f'You are running a project network with {n} nodes as you setup')
        G=project_network_generater_v2.project_network_generater(n)
    elif x!=[] and n!=30:
        print('ERRO!Please do not enter x and n simutanously!')
    elif x==[] and n==30:
        print('You are running a project network with 30 nodes as default')
        G=project_network_generater_v2.project_network_generater(n)
    else:
        tt=list(map(len,x))
        TT=list(tt[0]*np.ones(len(tt)))
        if TT==tt:
            G=np.array(x)
            print(f'You are running a project network with {tt[0]} nodes as you setup')
        else:
            print('define a n x n matrix with n list, each list has n element, make sure it is a project network maatrix')
    EET=get_EETs.get_EETs(G)
    LET=get_LETs.get_LETs(G,EET)
    TFs_Dict=get_TFs.get_TFs(G,EET,LET)
    critical_Path=[]
    for i in list(TFs_Dict.keys()):
        if TFs_Dict[i]==0:
            critical_Path.append(i)
    count=0
    for i in critical_Path:
        if eval(i)[0]==1:
            count+=1
    print(count)
    CP=[]
    for i in range(count):
        L=['path'+str(i+1)]
        L.append(eval(critical_Path[i]))
        for j in critical_Path:
            if eval(j)[0]==L[-1][-1]:
                L.append(eval(j))
            else:
                continue
        print(f'The NO.{i+1} critical path of this project network is {L}')
        CP.append(L)
    
    return CP

In [438]:
My_CPM(x=[[1,2,3],[1,3]])

define a n x n matrix with n list, each list has n element, make sure it is a project network maatrix


UnboundLocalError: local variable 'G' referenced before assignment

In [111]:
xx=[[-1,4,-1,-1],[-1,-1,7,10],[-1,-1,-1,1],[-1,-1,-1,-1]]
y=list(map(len,xx))
yx=list(y[0]*np.ones(len(y)))
yx==y

True

In [5]:
from random import randint
import numpy as np

def project_network_generater(n=30):
    G=np.ones((n,n))
    G*=-1
# Make sure node 1 :node n has a full connected path
    for i in range(n):
        for j in range(i+1,n):
            G[i,j]=randint(-1,10)
    for i in range(n-1):
        j=i+1
        G[i,j]=randint(0,10)
# Ensuring at most 4 income
    for i in range(5,n):
        popout_List=[]
        while len(popout_List)<i-4:
            random_Popout_Index=randint(0,i-2)
            if  random_Popout_Index in popout_List:
                continue
            else:
                popout_List.append(random_Popout_Index)
        for item in popout_List:
            G[item,i]=-1
    return G

In [7]:
project_network_generater(9)

array([[-1.,  3.,  6.,  5.,  1., -1.,  0., -1., -1.],
       [-1., -1.,  7.,  2.,  9., -1., -1., 10., -1.],
       [-1., -1., -1.,  2.,  4.,  9.,  8., -1.,  7.],
       [-1., -1., -1., -1.,  5.,  5., -1., -1.,  6.],
       [-1., -1., -1., -1., -1.,  5.,  3., -1., -1.],
       [-1., -1., -1., -1., -1., -1.,  1.,  0.,  4.],
       [-1., -1., -1., -1., -1., -1., -1.,  2., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1.,  3.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1.]])

In [1]:
import numpy as np

In [3]:
x=np.ones((4,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
type(x)==type(np.ones((1,1)))

True